import { Pool } from "pg";
import type { DeviceInfo, EnvironmentalReading, LoginResponse } from "../../shared/types";

const apiBase = (process.env.SOURCE_API_BASE ?? "https://team2.up.railway.app/api").replace(/\/$/, "");
const adminEmail = process.env.SOURCE_ADMIN_EMAIL ?? "admin@email.com";
const adminPassword = process.env.SOURCE_ADMIN_PASSWORD ?? "admin";
const databaseUrl = process.env.DATABASE_URL?.trim();
const windowDays = Math.max(1, Number.parseInt(process.env.MIGRATION_WINDOW_DAYS ?? "30", 10) || 30);
const sourceFrom = process.env.SOURCE_FROM ?? "2020-01-01T00:00:00.000Z";
const sourceTo = process.env.SOURCE_TO ?? new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString();

if (!databaseUrl) {
  throw new Error("DATABASE_URL is required. Set it to the Railway PostgreSQL connection string.");
}

async function fetchJson<T>(url: string, options: RequestInit = {}): Promise<T> {
  const response = await fetch(url, options);
  if (!response.ok) {
    const body = await response.text();
    throw new Error(`${response.status} ${response.statusText} from ${url}: ${body.slice(0, 500)}`);
  }
  return response.json() as Promise<T>;
}

async function login(): Promise<string> {
  const response = await fetchJson<LoginResponse>(`${apiBase}/auth/login`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ email: adminEmail, password: adminPassword }),
  });
  return response.token;
}

async function ensureSchema(pool: Pool): Promise<void> {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS readings (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      device_id TEXT NOT NULL,
      timestamp TEXT NOT NULL,
      co2_ppm REAL NOT NULL,
      temperature_c REAL NOT NULL,
      humidity_pct REAL NOT NULL,
      pressure_hpa REAL NOT NULL,
      light_lux REAL NOT NULL,
      sound_level_adc REAL NOT NULL,
      sound_peak_adc REAL DEFAULT 0,
      sound_rms_adc REAL DEFAULT 0,
      sound_event INTEGER DEFAULT 0,
      battery_v REAL,
      gateway_id TEXT,
      source TEXT
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS devices (
      device_id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      location TEXT NOT NULL,
      last_seen TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'offline',
      firmware_version TEXT,
      battery_v REAL,
      monitoring_enabled INTEGER NOT NULL DEFAULT 1,
      monitoring_command_seq INTEGER NOT NULL DEFAULT 0,
      monitoring_updated_at TEXT,
      measurement_started_at TEXT
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id TEXT PRIMARY KEY,
      email TEXT NOT NULL UNIQUE,
      name TEXT NOT NULL,
      role TEXT NOT NULL,
      password TEXT NOT NULL,
      google_id TEXT,
      avatar_url TEXT,
      timezone TEXT NOT NULL DEFAULT 'Europe/Prague',
      auth_provider TEXT NOT NULL DEFAULT 'password'
    )
  `);

  await pool.query("CREATE INDEX IF NOT EXISTS idx_readings_device_time ON readings (device_id, timestamp)");
  await pool.query("CREATE INDEX IF NOT EXISTS idx_readings_timestamp ON readings (timestamp)");
  await pool.query(`
    INSERT INTO users (id, email, name, role, password, timezone)
    VALUES
      ('usr-admin', 'admin@email.com', 'Admin', 'admin', 'admin', 'Europe/Prague'),
      ('usr-uzivatel1', 'uzivatel1@email.com', 'uzivatel1', 'viewer', 'uzivatel1', 'Europe/Prague')
    ON CONFLICT(id) DO UPDATE SET
      email = EXCLUDED.email,
      role = EXCLUDED.role,
      password = EXCLUDED.password
  `);
}

async function upsertDevice(pool: Pool, device: DeviceInfo): Promise<void> {
  await pool.query(
    `INSERT INTO devices (
       device_id, name, location, last_seen, status, firmware_version, battery_v,
       monitoring_enabled, monitoring_command_seq, monitoring_updated_at, measurement_started_at
     )
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
     ON CONFLICT(device_id) DO UPDATE SET
       name = EXCLUDED.name,
       location = EXCLUDED.location,
       last_seen = EXCLUDED.last_seen,
       status = EXCLUDED.status,
       firmware_version = EXCLUDED.firmware_version,
       battery_v = EXCLUDED.battery_v,
       monitoring_enabled = EXCLUDED.monitoring_enabled,
       monitoring_command_seq = EXCLUDED.monitoring_command_seq,
       monitoring_updated_at = EXCLUDED.monitoring_updated_at,
       measurement_started_at = EXCLUDED.measurement_started_at`,
    [
      device.device_id,
      device.name,
      device.location,
      device.last_seen,
      device.status,
      device.firmware_version ?? null,
      device.battery_v ?? null,
      device.monitoring_enabled === false ? 0 : 1,
      device.monitoring_command_seq ?? 0,
      device.monitoring_updated_at ?? null,
      device.measurement_started_at ?? null,
    ]
  );
}

async function insertReadingIfMissing(pool: Pool, reading: EnvironmentalReading): Promise<boolean> {
  const existing = await pool.query(
    "SELECT 1 FROM readings WHERE device_id = $1 AND timestamp = $2 AND COALESCE(source, '') = COALESCE($3, '') LIMIT 1",
    [reading.device_id, reading.timestamp, reading.source ?? null]
  );
  if (existing.rowCount > 0) return false;

  await pool.query(
    `INSERT INTO readings (
       device_id, timestamp, co2_ppm, temperature_c, humidity_pct, pressure_hpa,
       light_lux, sound_level_adc, sound_peak_adc, sound_rms_adc, sound_event,
       battery_v, gateway_id, source
     )
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)`,
    [
      reading.device_id,
      reading.timestamp,
      reading.co2_ppm,
      reading.temperature_c,
      reading.humidity_pct,
      reading.pressure_hpa,
      reading.light_lux,
      reading.sound_level_adc,
      reading.sound_peak_adc ?? 0,
      reading.sound_rms_adc ?? 0,
      reading.sound_event ? 1 : 0,
      reading.battery_v ?? null,
      reading.gateway_id ?? null,
      reading.source ?? null,
    ]
  );
  return true;
}

function addDays(date: Date, days: number): Date {
  return new Date(date.getTime() + days * 24 * 60 * 60 * 1000);
}

async function fetchReadingsWindow(token: string, from: Date, to: Date): Promise<EnvironmentalReading[]> {
  const params = new URLSearchParams({
    from: from.toISOString(),
    to: to.toISOString(),
    limit: "100000",
  });
  return fetchJson<EnvironmentalReading[]>(`${apiBase}/readings?${params.toString()}`, {
    headers: { Authorization: `Bearer ${token}` },
  });
}

async function main(): Promise<void> {
  console.log(`[Migration] Source API: ${apiBase}`);
  console.log(`[Migration] Range: ${sourceFrom} -> ${sourceTo}`);

  const token = await login();
  const pool = new Pool({
    connectionString: databaseUrl,
    ssl: process.env.PGSSL === "false" ? false : { rejectUnauthorized: false },
  });

  try {
    await ensureSchema(pool);

    const devices = await fetchJson<DeviceInfo[]>(`${apiBase}/devices`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    for (const device of devices) {
      await upsertDevice(pool, device);
    }
    console.log(`[Migration] Upserted ${devices.length} devices`);

    let inserted = 0;
    let skipped = 0;
    let totalFetched = 0;
    let windowStart = new Date(sourceFrom);
    const end = new Date(sourceTo);
    if (Number.isNaN(windowStart.getTime()) || Number.isNaN(end.getTime())) {
      throw new Error("SOURCE_FROM and SOURCE_TO must be valid ISO dates.");
    }

    while (windowStart < end) {
      const windowEnd = addDays(windowStart, windowDays);
      const boundedEnd = windowEnd < end ? windowEnd : end;
      const readings = await fetchReadingsWindow(token, windowStart, boundedEnd);
      totalFetched += readings.length;
      if (readings.length >= 100000) {
        console.warn(`[Migration] Window hit API cap: ${windowStart.toISOString()} -> ${boundedEnd.toISOString()}`);
      }
      for (const reading of readings) {
        if (await insertReadingIfMissing(pool, reading)) inserted++;
        else skipped++;
      }
      console.log(
        `[Migration] ${windowStart.toISOString()} -> ${boundedEnd.toISOString()}: fetched=${readings.length}, inserted=${inserted}, skipped=${skipped}`
      );
      windowStart = boundedEnd;
    }

    console.log(`[Migration] Done. fetched=${totalFetched}, inserted=${inserted}, skipped=${skipped}`);
  } finally {
    await pool.end();
  }
}

main().catch((error) => {
  console.error("[Migration] Failed:", error);
  process.exit(1);
});
